# Generated by Django 5.2.7 on 2025-12-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.BigIntegerField(default=0, verbose_name='موجودی کیف پول (تومان)'),
        ),
    ]
