# Generated by Django 5.2.8 on 2025-11-10 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت هواپیمایی')),
            ],
            options={
                'verbose_name': 'شرکت هواپیمایی',
                'verbose_name_plural': 'شرکت\u200cهای هواپیمایی',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر/فرودگاه')),
                ('code', models.CharField(help_text='کد 3 حرفی اختصاصی (مثلا THR)', max_length=3, unique=True, verbose_name='کد اختصاصی')),
            ],
            options={
                'verbose_name': 'فرودگاه',
                'verbose_name_plural': 'فرودگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='flights.airport', verbose_name='مقصد')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='flights.airport', verbose_name='مبدأ')),
            ],
            options={
                'verbose_name': 'مسیر',
                'verbose_name_plural': 'مسیرها',
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='تاریخ و ساعت پرواز')),
                ('arrival_time', models.DateTimeField(verbose_name='تاریخ و ساعت رسیدن')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('total_seats', models.PositiveIntegerField(verbose_name='ظرفیت کل صندلی')),
                ('available_seats', models.PositiveIntegerField(verbose_name='صندلی\u200cهای باقیمانده')),
                ('cancellation_fee_percent', models.DecimalField(decimal_places=2, default=0.2, help_text='مثلا 0.20 برای ۲۰ درصد جریمه', max_digits=5, verbose_name='درصد جریمه کنسلی')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline', verbose_name='شرکت پروازی')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.route', verbose_name='مسیر')),
            ],
            options={
                'verbose_name': 'پرواز',
                'verbose_name_plural': 'پروازها',
                'ordering': ['departure_time'],
            },
        ),
    ]
