# Generated by Django 5.2.7 on 2025-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airplane_type',
            field=models.CharField(default='Boeing 737', max_length=50),
        ),
    ]
