# Generated by Django 5.2.8 on 2025-11-10 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('purchased_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت در لحظه خرید')),
                ('status', models.CharField(choices=[('PUR', 'خریداری شده'), ('CAN', 'کنسل شده')], default='PUR', max_length=3, verbose_name='وضعیت رزرو')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.flight', verbose_name='پرواز (محصول)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر (خریدار)')),
            ],
            options={
                'verbose_name': 'رزرو (بلیط)',
                'verbose_name_plural': 'رزروها (بلیط\u200cها)',
            },
        ),
    ]
